[package]
name = "FinSc-Hadron"
version = "0.3.0"
ipkg = "FinSc-Hadron.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Physics]
type = "local"
path = "../FinSc-Physics"
ipkg = "FinSc-Physics.ipkg"
